version: '2'

services:
    agent:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/app
        ports:
            - 8000:8000
        container_name: agent